# Generated by Django 4.2.29 on 2026-03-29 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the workspace', max_length=100)),
                ('slug', models.SlugField(help_text='Unique URL-friendly identifier', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the workspace')),
                ('is_public', models.BooleanField(default=False, help_text='Whether the workspace is publicly discoverable')),
                ('allow_guests', models.BooleanField(default=True, help_text='Whether guests can be invited to this workspace')),
                ('icon_url', models.URLField(blank=True, help_text='Workspace icon URL', null=True)),
                ('invite_code', models.CharField(blank=True, help_text='Unique code for joining the workspace', max_length=32, null=True, unique=True)),
                ('invite_code_expires_at', models.DateTimeField(blank=True, help_text='When the invite code expires', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the workspace is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='User who created and owns this workspace', on_delete=django.db.models.deletion.CASCADE, related_name='owned_workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'workspace',
                'verbose_name_plural': 'workspaces',
                'db_table': 'workspaces',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', help_text='Role of the user in this workspace', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the membership is active')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('invited_at', models.DateTimeField(blank=True, help_text='When the invitation was sent', null=True)),
                ('notify_mentions', models.BooleanField(default=True)),
                ('notify_all_messages', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_by', models.ForeignKey(blank=True, help_text='User who invited this member', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invites', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='The member user', on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memberships', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(help_text='The workspace', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='domain.workspace')),
            ],
            options={
                'verbose_name': 'workspace membership',
                'verbose_name_plural': 'workspace memberships',
                'db_table': 'workspace_memberships',
                'ordering': ['-joined_at'],
                'indexes': [models.Index(fields=['workspace', 'is_active'], name='workspace_m_workspa_2a7a3e_idx'), models.Index(fields=['user', 'is_active'], name='workspace_m_user_id_e10463_idx')],
                'unique_together': {('workspace', 'user')},
            },
        ),
        migrations.CreateModel(
            name='WorkspaceInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address of the invited user', max_length=254)),
                ('token', models.CharField(help_text='Unique invitation token', max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(help_text='User who sent the invitation', on_delete=django.db.models.deletion.CASCADE, related_name='workspace_invites_sent', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(help_text='The workspace being invited to', on_delete=django.db.models.deletion.CASCADE, related_name='pending_invites', to='domain.workspace')),
            ],
            options={
                'verbose_name': 'workspace invite',
                'verbose_name_plural': 'workspace invites',
                'db_table': 'workspace_invites',
                'ordering': ['-created_at'],
                'unique_together': {('workspace', 'email')},
            },
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['slug'], name='workspaces_slug_cac896_idx'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['owner'], name='workspaces_owner_i_04111b_idx'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['is_active'], name='workspaces_is_acti_88a65d_idx'),
        ),
    ]
