# Generated by Django 4.2.29 on 2026-03-29 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_workspace_workspacemembership_workspaceinvite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Channel name (without the #)', max_length=80)),
                ('normalized_name', models.CharField(help_text='Lowercase name for uniqueness checks', max_length=80)),
                ('channel_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', help_text='Public channels are visible to all workspace members', max_length=10)),
                ('topic', models.CharField(blank=True, help_text='Brief topic shown at the top of the channel', max_length=250)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the channel purpose')),
                ('is_default', models.BooleanField(default=False, help_text='Is this the default #general channel')),
                ('is_archived', models.BooleanField(default=False, help_text='Archived channels are read-only')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, help_text='When the channel was archived', null=True)),
                ('created_by', models.ForeignKey(help_text='User who created this channel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_channels', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(help_text='The workspace this channel belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='domain.workspace')),
            ],
            options={
                'verbose_name': 'channel',
                'verbose_name_plural': 'channels',
                'db_table': 'channels',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Message content (supports markdown-like formatting)')),
                ('is_thread_reply', models.BooleanField(default=False, help_text='Is this a reply in a thread')),
                ('is_edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(help_text='The channel this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='domain.channel')),
                ('parent_message', models.ForeignKey(blank=True, help_text='Parent message for thread replies', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='domain.message')),
                ('sender', models.ForeignKey(help_text='User who sent the message', on_delete=django.db.models.deletion.CASCADE, related_name='messages_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'db_table': 'messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['channel', 'created_at'], name='messages_channel_68995e_idx'), models.Index(fields=['sender', 'created_at'], name='messages_sender__bf8b1c_idx'), models.Index(fields=['parent_message', 'created_at'], name='messages_parent__0b80e6_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChannelMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the membership is active')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('notify_all_messages', models.BooleanField(default=False, help_text='Notify on all messages (default: only mentions)')),
                ('muted', models.BooleanField(default=False, help_text='Mute this channel')),
                ('last_read_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Last time user read messages in this channel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(help_text='The channel', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='domain.channel')),
                ('invited_by', models.ForeignKey(blank=True, help_text='User who invited this member (null if joined public channel)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_invites_sent', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='The member', on_delete=django.db.models.deletion.CASCADE, related_name='channel_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'channel membership',
                'verbose_name_plural': 'channel memberships',
                'db_table': 'channel_memberships',
                'ordering': ['-joined_at'],
                'indexes': [models.Index(fields=['channel', 'is_active'], name='channel_mem_channel_aedf7e_idx'), models.Index(fields=['user', 'is_active'], name='channel_mem_user_id_65560c_idx')],
                'unique_together': {('channel', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['workspace', 'channel_type'], name='channels_workspa_f2b0ac_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['workspace', 'is_archived'], name='channels_workspa_893f5d_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['normalized_name'], name='channels_normali_2ad529_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together={('workspace', 'normalized_name')},
        ),
    ]
