# Generated by Django 4.2.29 on 2026-03-29 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0003_channel_message_channelmembership_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectMessageConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_group', models.BooleanField(default=False, help_text='Is this a group DM (more than 2 people)')),
                ('name', models.CharField(blank=True, help_text='Optional name for group DMs', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this conversation is active')),
                ('is_archived', models.BooleanField(default=False, help_text='Archived conversations are hidden from the list')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the last message was sent')),
                ('last_message_preview', models.CharField(blank=True, help_text='Preview of the last message', max_length=200)),
                ('created_by', models.ForeignKey(help_text='User who created this conversation', on_delete=django.db.models.deletion.CASCADE, related_name='created_dm_conversations', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(help_text='The workspace this DM belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='dm_conversations', to='domain.workspace')),
            ],
            options={
                'verbose_name': 'DM conversation',
                'verbose_name_plural': 'DM conversations',
                'db_table': 'dm_conversations',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Message content')),
                ('is_thread_reply', models.BooleanField(default=False, help_text='Is this a reply in a thread')),
                ('is_edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(help_text='The conversation this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='domain.directmessageconversation')),
                ('parent_message', models.ForeignKey(blank=True, help_text='Parent message for thread replies', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='domain.directmessage')),
                ('sender', models.ForeignKey(help_text='User who sent the message', on_delete=django.db.models.deletion.CASCADE, related_name='direct_messages_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'direct message',
                'verbose_name_plural': 'direct messages',
                'db_table': 'direct_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(help_text='Emoji unicode or shortcode (e.g., ":thumbsup:")', max_length=50)),
                ('emoji_name', models.CharField(blank=True, help_text='Name of the emoji for custom emojis', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(help_text='The message being reacted to', on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='domain.message')),
                ('user', models.ForeignKey(help_text='User who reacted', on_delete=django.db.models.deletion.CASCADE, related_name='message_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'message reaction',
                'verbose_name_plural': 'message reactions',
                'db_table': 'message_reactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['message', 'emoji'], name='message_rea_message_7f9ef3_idx'), models.Index(fields=['user', 'created_at'], name='message_rea_user_id_096006_idx')],
                'unique_together': {('message', 'user', 'emoji')},
            },
        ),
        migrations.CreateModel(
            name='FileAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='The uploaded file', upload_to='attachments/%Y/%m/')),
                ('file_name', models.CharField(help_text='Original file name', max_length=255)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(help_text='MIME type of the file', max_length=100)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('code', 'Code'), ('archive', 'Archive'), ('other', 'Other')], default='other', help_text='Category of the file', max_length=20)),
                ('width', models.PositiveIntegerField(blank=True, help_text='Image width in pixels', null=True)),
                ('height', models.PositiveIntegerField(blank=True, help_text='Image height in pixels', null=True)),
                ('thumbnail_url', models.URLField(blank=True, help_text='URL to thumbnail image', null=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Whether the file has been deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direct_message', models.ForeignKey(blank=True, help_text='The DM this file is attached to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='domain.directmessage')),
                ('message', models.ForeignKey(blank=True, help_text='The channel message this file is attached to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='domain.message')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded the file', on_delete=django.db.models.deletion.CASCADE, related_name='file_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'file attachment',
                'verbose_name_plural': 'file attachments',
                'db_table': 'file_attachments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['message', 'created_at'], name='file_attach_message_db1d59_idx'), models.Index(fields=['direct_message', 'created_at'], name='file_attach_direct__79388b_idx'), models.Index(fields=['uploaded_by', 'created_at'], name='file_attach_uploade_198bff_idx'), models.Index(fields=['file_type'], name='file_attach_file_ty_60971e_idx')],
            },
        ),
        migrations.CreateModel(
            name='DirectMessageParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the participant is still in the conversation')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, help_text='When the participant left', null=True)),
                ('muted', models.BooleanField(default=False, help_text='Mute this conversation')),
                ('notify_mentions_only', models.BooleanField(default=False, help_text='Only notify on mentions')),
                ('last_read_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Last time user read messages')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, help_text='Who added this participant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dm_users_added', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(help_text='The conversation', on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='domain.directmessageconversation')),
                ('user', models.ForeignKey(help_text='The participant', on_delete=django.db.models.deletion.CASCADE, related_name='dm_participants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DM participant',
                'verbose_name_plural': 'DM participants',
                'db_table': 'dm_participants',
                'ordering': ['-joined_at'],
                'indexes': [models.Index(fields=['conversation', 'is_active'], name='dm_particip_convers_6c1b69_idx'), models.Index(fields=['user', 'is_active'], name='dm_particip_user_id_c0c11f_idx')],
                'unique_together': {('conversation', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='directmessageconversation',
            index=models.Index(fields=['workspace', 'is_active'], name='dm_conversa_workspa_7675fc_idx'),
        ),
        migrations.AddIndex(
            model_name='directmessageconversation',
            index=models.Index(fields=['workspace', 'created_by'], name='dm_conversa_workspa_2d3c7d_idx'),
        ),
        migrations.AddIndex(
            model_name='directmessageconversation',
            index=models.Index(fields=['last_message_at'], name='dm_conversa_last_me_dbf5ff_idx'),
        ),
        migrations.AddIndex(
            model_name='directmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='direct_mess_convers_b9403f_idx'),
        ),
        migrations.AddIndex(
            model_name='directmessage',
            index=models.Index(fields=['sender', 'created_at'], name='direct_mess_sender__13fade_idx'),
        ),
        migrations.AddIndex(
            model_name='directmessage',
            index=models.Index(fields=['parent_message', 'created_at'], name='direct_mess_parent__3d8dd4_idx'),
        ),
    ]
