# Generated by Django 4.2.29 on 2026-03-31 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0004_directmessageconversation_directmessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mention_type', models.CharField(choices=[('user', 'User Mention'), ('channel', 'Channel Mention (@channel)'), ('here', 'Here Mention (@here)'), ('everyone', 'Everyone Mention (@everyone)')], default='user', help_text='Type of mention', max_length=20)),
                ('mention_text', models.CharField(help_text='Original mention text', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'mention',
                'verbose_name_plural': 'mentions',
                'db_table': 'mentions',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('mention', 'Mention'), ('channel_message', 'Channel Message'), ('dm_message', 'Direct Message'), ('reaction', 'Reaction'), ('thread_reply', 'Thread Reply'), ('workspace_invite', 'Workspace Invite'), ('channel_invite', 'Channel Invite')], help_text='Type of notification', max_length=30)),
                ('title', models.CharField(help_text='Notification title', max_length=200)),
                ('body', models.TextField(blank=True, help_text='Notification body/preview', max_length=500)),
                ('is_read', models.BooleanField(default=False, help_text='Whether the notification has been read')),
                ('read_at', models.DateTimeField(blank=True, help_text='When the notification was read', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['channel', 'is_deleted', 'created_at'], name='messages_channel_3697f2_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_deleted', 'created_at'], name='messages_is_dele_0bea0e_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='users_usernam_baeb4b_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['display_name'], name='users_display_32b2ed_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'last_active'], name='users_is_acti_e96b0e_idx'),
        ),
        migrations.AddField(
            model_name='notification',
            name='channel',
            field=models.ForeignKey(blank=True, help_text='Related channel', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='domain.channel'),
        ),
        migrations.AddField(
            model_name='notification',
            name='direct_message',
            field=models.ForeignKey(blank=True, help_text='Related direct message', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='domain.directmessage'),
        ),
        migrations.AddField(
            model_name='notification',
            name='dm_conversation',
            field=models.ForeignKey(blank=True, help_text='Related DM conversation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='domain.directmessageconversation'),
        ),
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.ForeignKey(blank=True, help_text='Related channel message', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='domain.message'),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(help_text='User who receives the notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, help_text='User who triggered the notification', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='workspace',
            field=models.ForeignKey(blank=True, help_text='Related workspace', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='domain.workspace'),
        ),
        migrations.AddField(
            model_name='mention',
            name='direct_message',
            field=models.ForeignKey(blank=True, help_text='Direct message with the mention', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='domain.directmessage'),
        ),
        migrations.AddField(
            model_name='mention',
            name='mentioned_user',
            field=models.ForeignKey(blank=True, help_text='User who was mentioned (null for @channel/@here)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentions_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mention',
            name='message',
            field=models.ForeignKey(blank=True, help_text='Channel message with the mention', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='domain.message'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_dde14f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'notification_type'], name='notificatio_recipie_b1a229_idx'),
        ),
        migrations.AddIndex(
            model_name='mention',
            index=models.Index(fields=['message', 'mention_type'], name='mentions_message_6a04d6_idx'),
        ),
        migrations.AddIndex(
            model_name='mention',
            index=models.Index(fields=['direct_message', 'mention_type'], name='mentions_direct__322a68_idx'),
        ),
        migrations.AddIndex(
            model_name='mention',
            index=models.Index(fields=['mentioned_user', '-created_at'], name='mentions_mention_2a5326_idx'),
        ),
    ]
